export const SEARCH_FIELD_CHANGED = "SEARCH_FIELD_CHANGED";

export const REQUEST_PRODUCTS_PENDING = "REQUEST_PRODUCTS_PENDING";

export const REQUEST_PRODUCTS_SUCCESS = "REQUEST_PRODUCTS_SUCCESS";

export const REQUEST_PRODUCTS_FAILED = "REQUEST_PRODUCTS_FAILED";

export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
